### ISSUE TITLE
Object is .Gjs_FavouriteConnectionsBox.prototype, not an object instance - cannot convert to GObject*

### ISSUE THREAD

**Issue by ato10** [bo32/gnome-shell-extension-isshu#2]
Hi, I've got the following error on Ubuntu 17.04 shel 3.24.2

`JS ERROR: Exception in callback for signal: extension-found: Error: Object is .Gjs_FavouriteConnectionsBox.prototype, not an object instance - cannot convert to GObject*
init/Clutter.Actor.prototype.toString@resource:///org/gnome/shell/ui/environment.js:103:16
_addSignalMethod@resource:///org/gnome/gjs/modules/signals.js:145:1
addSignalMethods@resource:///org/gnome/gjs/modules/signals.js:152:5
@/home/user/.local/share/gnome-shell/extensions/isshu@bo32.github.com/favourite_connections_box.js:118:1
@/home/user/.local/share/gnome-shell/extensions/isshu@bo32.github.com/new_connection_dialog.js:12:7
@/home/user/.local/share/gnome-shell/extensions/isshu@bo32.github.com/extension.js:12:7
initExtension@resource:///org/gnome/shell/ui/extensionSystem.js:221:5
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:168:18
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:312:9
_emit@resource:///org/gnome/gjs/modules/signals.js:126:27
ExtensionFinder<._loadExtension@resource:///org/gnome/shell/misc/extensionUtils.js:184:9
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
bind/<@resource:///org/gnome/gjs/modules/lang.js:95:16
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:1
ExtensionFinder<.scanExtensions@resource:///org/gnome/shell/misc/extensionUtils.js:189:9
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:314:5
enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:322:9
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:353:9
init@resource:///org/gnome/shell/ui/extensionSystem.js:361:5
_initializeUI@resource:///org/gnome/shell/ui/main.js:219:5
start@resource:///org/gnome/shell/ui/main.js:127:5
@<main>:1:31
`

**Comment by bo32** [comment]
Can you please try to help me reproducing the bug? What did you do for this error?

**Comment by ato10** [comment]
I cannot install extension using https://extensions.gnome.org/
so I try to clone git:master in ~/.local/share/gnome-shell/extensions/isshu@bo32.github.com/
compile schemas and when i restart the shell (ALT+F2 -> r) i have this error

**Comment by bo32** [comment]
please have a look at this commit.
This is issue was due to some changes in Gnome-shell 3.24. Please have a look at the 2 last commits and clone the latest version. 
Let me know if you still have the issue.

**Comment by ato10** [comment]
Hi, sorry for the late response.
Now i've got this error
`Extension "isshu@bo32.github.com" had error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`
after shell restart.
I found an empty config file ~/.isshu/saved_data.json then I tried to insert an empty array {}
Now I can enable the extension but I cannot connect or save any favourite
`JS ERROR: TypeError: latest is undefined
SavedConfiguration<.save_connection_as_a_latest@/home/user/.local/share/gnome-shell/extensions/isshu@bo32.github.com/saved_configuration.js:48:1
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
NewConnectionDialog<.connect_ssh@/home/user/.local/share/gnome-shell/extensions/isshu@bo32.github.com/new_connection_dialog.js:252:9
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22`

**Comment by bo32** [comment]
Hi, sorry for all the issues... but it's fairly new :)
I pushed a change that inits the json file. So you can pull the latest changes and refresh the extension.
If you added some content in the saved_data.json file, please remove it (or simply delete the file, it will be re-created).

**Comment by ato10** [comment]
Never mind, thanks to working on it.
Now it works on ubuntu and on my archlinux (shell 3.25.91) too

**Comment by bo32** [comment]
great :D
