### ISSUE TITLE
-X -Y connections

### ISSUE THREAD

**Issue by ShapopiJ** [bo32/gnome-shell-extension-isshu#20]
All works fine. 
I would just like all connections to open with -X or -Y options.
Please help super new to all this!

**Comment by bo32** [comment]
Hi, I just created a new branch **issues/20** with the option for that; I basically added a new field where you can enter all the SSH options you want (this field is by default hidden, you need to enable it in the Preferences menu).
I also added a button where you can see what your SSH looks like before clicking on Connect (could be convenient especially in your case).

Please let me know what you think of it, so I can merge the feature for a new release.

**Comment by ShapopiJ** [comment]
Thanks David it works like a gem!!

**Comment by bo32** [comment]
Good to hear :) I'll try to merge and publish the new version on the Gnome Shell Extensions site as soon as I can.

**Comment by ShapopiJ** [comment]
I'm not sure if I made a mistake or whether something else is wrong, but the terminals don't open any more. Only upon the first connection they open but never again. What am I doing wrong?

**Comment by bo32** [comment]
try to use the See command button and run it manually in a terminal.
I know that this extension doesn't always cope well with the errors returned by the SSH command.

**Comment by ShapopiJ** [comment]
In a separate terminal the command works well, as it should. The terminals just won't open when I open them under the "latest connections" dropdown.

**Comment by bo32** [comment]
I fixed that. please check the master branch. The fix is submitted to the GnomeShell extensions website, needs to be approved.
