### ISSUE TITLE
Cannot install on gnome 3.32.0

### ISSUE THREAD

**Issue by TheBigFatTony** [bo32/gnome-shell-extension-isshu#24]
Hi! Thanks for your great extension.

Sadly, it stopped working when I updated to Fedora 30 beta running gnome `3.32.0`.

This is the log I got from `journalctl /usr/bin/gnome-shell -f -o cat` when I tried to install it:

```
Archive:  /tmp/3EAWZZ.shell-extension.zip
  inflating: /home/thomas/.local/share/gnome-shell/extensions/isshu@bo32.github.com/prefs.js
  inflating: /home/thomas/.local/share/gnome-shell/extensions/isshu@bo32.github.com/menus/connections_menu.js

...

  inflating: /home/thomas/.local/share/gnome-shell/extensions/isshu@bo32.github.com/menus/known_hosts_menu.js
 extracting: /home/thomas/.local/share/gnome-shell/extensions/isshu@bo32.github.com/metadata.json
Extension "isshu@bo32.github.com" had error: TypeError: this._construct is not a function
```

**Comment by yochaigal** [comment]
I can confirm this bug on Ubuntu 19.04:
Extension "isshu@bo32.github.com" had error: TypeError: this._construct is not a function

**Comment by bo32** [comment]
hey, took me some time but please have a look at the master branch. I just published the required changes for the GJS update.
The package is not yet available on the Gnome Shell Extensions website yet - needs to be approved first.

**Comment by yochaigal** [comment]
I've installed the master (downloaded zip + unzip + rename isshu@bo32.github.com) and enabled via the command line. Nothing shows up in Gnome Shell.

**Comment by bo32** [comment]
Mmmmh...
The extension has been approved on https://extensions.gnome.org/. Maybe you should try to install it via the website.
Otherwise, you can try to start gnome-shell and look at the logs by running in a terminal **gnome-shell --replace** (don't kill the process afterwards, just close and reopen the session) or via how @TheBigFatTony mentioned above and, let me know about the error message you find.

**Comment by yochaigal** [comment]
Hmm, yes it does work now, although the icon is missing (it's a dark space in the tray).

**Comment by bo32** [comment]
Strange, especially since the icon is supposed to be embedded in the extension :D
I'm a bit running out of ideas regarding the icon. Can you maybe try to switch Gnome-shell theme?
Or restart Gnome-shell?

**Comment by yochaigal** [comment]
I'm using the default shell theme. I logged out and logged back in as well. 

![noicon](https://user-images.githubusercontent.com/817479/58123516-f92b6080-7bd9-11e9-873f-5b692d38385b.png)

**Comment by bo32** [comment]
this is not my extension. Have a good one
