### ISSUE TITLE
"Error loading extension"

### ISSUE THREAD

**Issue by conspacer** [bo32/gnome-shell-extension-isshu#3]
"Error loading extension" triangle in tweak tool using beta release on GNOME Shell 3.24.2 (X11).
Whats the best to log exact error?

**Comment by bo32** [comment]
try to restart gnome-shell by executing: **gnome-shell --restart**
You will then see the logs of the different extension and the errors if there are any.

**Comment by bo32** [comment]
please check the last update changes on github (not available yet on gnome-shell extensions website)

**Comment by conspacer** [comment]
Yes! That works well now. Thanks.
