### ISSUE TITLE
[Feature Request] - Groups

### ISSUE THREAD

**Issue by returntrip** [bo32/gnome-shell-extension-isshu#4]
Hi, thanks for isshu! This looks really promising and I think it could become a great substitute to https://github.com/sciancio/connectionmanager2

Would love to see the introduction of groups to bundle ssh connections by type.

I like the prompt icon on the gnome bar, maybe you could use something similar as a logo for this project?

**Comment by bo32** [comment]
Thanks for the feedback! :)
I have to admit, my knowledge of SSH and its options is a bit limited. But I would love to keep improving the extension. What do you mean "by type"?

**Comment by returntrip** [comment]
NPS :)
What I mean is this: The user has the ability to create a group: "LAN Hosts". Under this group we put the hosts: "Raspberry PI1", "Home Server", "server.example.lan" etc etc

+>Group A
    |>>> Server 1
    |>>> Server 2
    |>>> Server 3

+> "LAN Hosts"
   |>>> "Raspberry PI1"
   |>>> "Home Server"
   |>>> "server.example.lan"


So that I can pick a certain host within a defined group. I think this would make things a bit more organised in the interface.

Hope it makes sense.

**Comment by bo32** [comment]
makes sense and seems interesting :)

**Comment by returntrip** [comment]
I am not a coder, is there any help I can provide? Translation etc???

**Comment by bo32** [comment]
Hi again, please have a look at my branch called *folders*. (you can pull or clone)
I made a very simple way of handling groups of connections, by inserting the name of the group in an extra optional field.

Regarding the translation, feel free :) I don't really have time to do it, I was not even thinking of implementing it.

**Comment by returntrip** [comment]
Thank seems to work fine :). Do you think we could line up the text of the connection with the Folder name?

Example:

(Folder Icon).LAN  <--- This is the folder name
(Spacing)......Home Server <--- This is the connection mame
.................... ^
.................... |
.................... |
.............Text Aligned

**Comment by bo32** [comment]
I guess that's possible... But I honestly don't think I will implement this. Might be a bit tricky to do - I don't know - and quite a detail.
Feel free to fork the project and do the change though :) I guess it's some CSS to apply. Here is the implementation of the menu: https://github.com/GNOME/gnome-shell/blob/master/js/ui/popupMenu.js
