### ISSUE TITLE
nmap scan doesn't work

### ISSUE THREAD

**Issue by monte-monte** [bo32/gnome-shell-extension-isshu#6]
Extension can't find installed nmap, because it uses `which --skip-alias nmap` to find if it's installed. https://github.com/bo32/gnome-shell-extension-isshu/blob/35f8967d14c3fa5cc8d5a068c4d7db2eb79ef09a/nmap_panel.js#L133
It seems, that on Ubuntu and Debian **which** doesn't have --skip-alias option and returns error: `Illegal option --`.

**Comment by bo32** [comment]
@monte-monte  please ignore my two commits on the develop branch, and check if it's working for you now.
I actually don't recall why I added `--skip-alias`... So I removed it.
