### ISSUE TITLE
Other terminal except gnome-termianl don't work

### ISSUE THREAD

**Issue by monte-monte** [bo32/gnome-shell-extension-isshu#7]
Other terminal I tried except gnome-termianl don't work because they don't support '--command' option. I see you have changed it to support telnet, but lost support of other terminals. https://github.com/bo32/gnome-shell-extension-isshu/blob/35f8967d14c3fa5cc8d5a068c4d7db2eb79ef09a/ssh_connection.js#L43

**Comment by bo32** [comment]
it's now fixed and merged in the develop branch.
Do you have any terminal in mind? please have a look at ssh_connection.js, for the list of the terminals that I have tested.
